version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd23
      POSTGRES_DB: BNSPDB
    networks:
      - springapipostgres-net
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - springapipostgres-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/BNSPDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd23

volumes:
  postgres-data:

networks:
  springapipostgres-net: