package bf.bnsp.api.tools.dataType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;

/**
 * @author Berickal
 */
@AllArgsConstructor
@Getter
public enum ECategoryIncident {

    CODE_000("FAUSSE_ALERTE", "MALVEILLANCE"),
    CODE_001("FAUSSE_ALERTE", "ERREUR"),
    CODE_101("FEUX", "Feu dans une maison d'habitation"),
    CODE_102("FEUX", "Feu de maison d'habitation"),
    CODE_103("FEUX", "Feu de boutique"),
    CODE_104("FEUX", "Feu de voiture"),
    CODE_105("FEUX", "Feu de camion citerne"),
    CODE_106("FEUX", "Feu de véhicule de transport en commun"),
    CODE_107("FEUX", "Feu de hangar"),
    CODE_108("FEUX", "Feu de coton ou graine de coton"),
    CODE_109("FEUX", "Feu de poubelle"),
    CODE_110("FEUX", "Feu de brousse"),
    CODE_111("FEUX", "Feu dans un atelier"),
    CODE_112("FEUX", "Feu dans un entrepôt"),
    CODE_113("FEUX", "Feu dans un ERP"),
    CODE_114("FEUX", "Feu de marché"),
    CODE_115("FEUX", "Feu dans un établissement industriel (usine)"),
    CODE_116("FEUX", "Feu dans un établissement sanitaire "),
    CODE_117("FEUX", "Feu de produits chimiques"),
    CODE_118("FEUX", "Feu dans un immeuble à usage administratif"),
    CODE_119("FEUX", "Feu dans un immeuble à usage d'habitation"),
    CODE_120("FEUX", "Feu dans un appartement"),
    CODE_121("FEUX", "Feu d'appartement"),
    CODE_122("FEUX", "Feu d'aéronef"),
    CODE_123("FEUX", "Feu de train"),
    CODE_124("FEUX", "Feu de mobylette"),
    CODE_125("FEUX", "Feu de station service"),
    CODE_126("FEUX", "Feu de dépôt d'hydrocarbures"),
    CODE_127("FEUX", "Feu de matières dangereuses"),
    CODE_128("FEUX", "Feu d'arbre"),
    CODE_129("FEUX", "Feu de charbon"),
    CODE_130("FEUX", "Feu de restaurant"),
    CODE_131("FEUX", "Feu de terrasse"),
    CODE_132("FEUX", "Feu de case d'escalier"),
    CODE_133("FEUX", "Feu de kiosque"),
    CODE_134("FEUX", "Feu de cuisine"),
    CODE_135("FEUX", "Feu de case, paille, foins, grenier, bois"),
    CODE_136("FEUX", "Feu de conteneur"),
    CODE_137("FEUX", "Feu de tricycle"),
    CODE_138("FEUX", "Feu de caterpillar"),
    CODE_139("FEUX", "Feu de vehicule transportant du gaz"),
    CODE_140("FEUX", "Feu de matiere plastique"),
    CODE_141("FEUX", "Feu de bureau"),
    CODE_142("FEUX", "Feu de personne"),
    CODE_143("FEUX", "Feu dans un cimetiere"),
    CODE_144("FEUX", "Feu de vehicule dans un garage"),
    CODE_145("FEUX", "Feu de papiers"),
    CODE_146("FEUX", "Feu de friteuse"),
    CODE_147("FEUX", "Feu de recolte"),
    CODE_148("FEUX", "Feu de metaux"),
    CODE_149("FEUX", "Feu de tissu"),
    CODE_150("FEUX", "Feu d'alcool"),
    CODE_151("FEUX", "Feu dans une poudriere"),
    CODE_152("FEUX", "Feu de noix (anacarde, karite, etc)"),
    CODE_153("FEUX", "Feu de pneus"),
    CODE_154("FEUX", "Feu de goudron"),
    CODE_155("FEUX", "Feu de gaz"),
    CODE_156("FEUX", "Feu de poteau electrique"),
    CODE_157("FEUX", "Feu de compteur electrique"),
    CODE_158("FEUX", "Feu d'appareil sous tension electrique"),
    CODE_159("FEUX", "Personne electrocutee"),
    CODE_160("FEUX", "Personne electrisee"),
    CODE_161("FEUX", "Foudre"),
    CODE_162("FEUX", "Feu de transformateur electrique"),
    CODE_163("FEUX", "Feu de cable electrique"),
    CODE_164("FEUX", "Feu suite a une explosion"),
    CODE_165("FEUX", "Feu de vehicule de transport de marchandise"),
    CODE_166("FEUX", "Feu de poulailler"),
    CODE_201("ACCIDENT_DE_CIRCULATION", "Deux roues # deux roues"),
    CODE_202("ACCIDENT_DE_CIRCULATION", "Deux roues #  vehicule"),
    CODE_203("ACCIDENT_DE_CIRCULATION", "Deux roues # animal"),
    CODE_204("ACCIDENT_DE_CIRCULATION", "Deux roues # objet fixe"),
    CODE_205("ACCIDENT_DE_CIRCULATION", "Deux roues # charrette"),
    CODE_206("ACCIDENT_DE_CIRCULATION", "Deux roues tombe seule"),
    CODE_207("ACCIDENT_DE_CIRCULATION", "Deux roues # train"),
    CODE_208("ACCIDENT_DE_CIRCULATION", "Vehicule # vehicule"),
    CODE_209("ACCIDENT_DE_CIRCULATION", "Vehicule # charrette"),
    CODE_210("ACCIDENT_DE_CIRCULATION", "Vehicule # animal"),
    CODE_211("ACCIDENT_DE_CIRCULATION", "Vehicule # objet fixe"),
    CODE_212("ACCIDENT_DE_CIRCULATION", "Vehicule renverse seul"),
    CODE_213("ACCIDENT_DE_CIRCULATION", "Vehicule # train"),
    CODE_214("ACCIDENT_DE_CIRCULATION", "Pieton # vehicule"),
    CODE_215("ACCIDENT_DE_CIRCULATION", "Pieton # roues"),
    CODE_216("ACCIDENT_DE_CIRCULATION", "Pieton # train"),
    CODE_217("ACCIDENT_DE_CIRCULATION", "Deraillement de train"),
    CODE_218("ACCIDENT_DE_CIRCULATION", "Collision entre deux train"),
    CODE_219("ACCIDENT_DE_CIRCULATION", "Tricycle # deux roues"),
    CODE_220("ACCIDENT_DE_CIRCULATION", "Tricycle # vehicule"),
    CODE_221("ACCIDENT_DE_CIRCULATION", "Tricycle # tricycle"),
    CODE_222("ACCIDENT_DE_CIRCULATION", "Tricycle # objet fixe"),
    CODE_223("ACCIDENT_DE_CIRCULATION", "Tricycle # animal"),
    CODE_224("ACCIDENT_DE_CIRCULATION", "Tricycle tombe seul"),
    CODE_225("ACCIDENT_DE_CIRCULATION", "Tricycle # charrette"),
    CODE_226("ACCIDENT_DE_CIRCULATION", "Vehicule # deux roues # tricycle"),
    CODE_227("ACCIDENT_DE_CIRCULATION", "Tricycle # pieton"),
    CODE_228("ACCIDENT_DE_CIRCULATION", "Tricycle # train"),
    CODE_229("ACCIDENT_DE_CIRCULATION", "Tricycle # deux roues # pieton"),
    CODE_230("ACCIDENT_DE_CIRCULATION", "Collision entre avion"),
    CODE_231("ACCIDENT_DE_CIRCULATION", "Vehicule # deux roues # pieton"),
    CODE_232("ACCIDENT_DE_CIRCULATION", "Pieton # plusieurs engins"),
    CODE_301("SECOURS_A_VICTIMES", "Intoxication (medicamenteuse, alimentaire, gaz, etc)"),
    CODE_302("SECOURS_A_VICTIMES", "Personne blessée par (arme, sport, rixe, animal, etc.)"),
    CODE_303("SECOURS_A_VICTIMES", "Personne mordue ou piquée par (un animal, insecte, reptile)"),
    CODE_304("SECOURS_A_VICTIMES", "Personne prise de malaise"),
    CODE_305("SECOURS_A_VICTIMES", "Personne coincée sous une charge"),
    CODE_306("SECOURS_A_VICTIMES", "Eboulement"),
    CODE_307("SECOURS_A_VICTIMES", "Personne tombée d'un arbre"),
    CODE_308("SECOURS_A_VICTIMES", "Personne tombée (d'une hauteur, seule)"),
    CODE_309("SECOURS_A_VICTIMES", "Bébé abandonné"),
    CODE_310("SECOURS_A_VICTIMES", "Pendaison"),
    CODE_311("SECOURS_A_VICTIMES", "Personne brûlée"),
    CODE_312("SECOURS_A_VICTIMES", "Femme en couche autre que EVASAN (Parturiente)"),
    CODE_313("SECOURS_A_VICTIMES", "Glissement de terrain"),
    CODE_314("SECOURS_A_VICTIMES", "EVASAN Femmes en couche CMA OU CSPS OU FMI / Hôpital"),
    CODE_315("SECOURS_A_VICTIMES", "EVASAN autre que Femmes en couche"),
    CODE_316("SECOURS_A_VICTIMES", "EVASAN Hôpital vers l'aéroport/ aéroport vers l'hôpital"),
    CODE_317("SECOURS_A_VICTIMES", "EVASAN Autres structures sanitaires (clinique) vers aéroport"),
    CODE_318("SECOURS_A_VICTIMES", "Personne tombée dans un puits, fosse, excavation"),
    CODE_319("SECOURS_A_VICTIMES", "Personne noyée en plan ou cours d'eau (Repêchage de corps)"),
    CODE_411("ASSISTANCE_A_PERSONNES", "Mise en sécurité de personne (s) lors d'un événement quelconque"),
    CODE_412("ASSISTANCE_A_PERSONNES", "Personne menaçant de se jeter dans le vide"),
    CODE_413("ASSISTANCE_A_PERSONNES", "Personne ne nécessitant pas transport à l'hôpital"),
    CODE_414("ASSISTANCE_A_PERSONNES", "Personne menaçant suicide"),
    CODE_415("ASSISTANCE_A_PERSONNES", "Brancardage"),
    CODE_416("ASSISTANCE_A_PERSONNES", "Maitrise d'un forcené ou d'un aliéné"),
    CODE_421("ASSISTANCE_A_PERSONNES", "Ouverture de porte avec une personne à l'intérieure"),
    CODE_422("ASSISTANCE_A_PERSONNES", "Personne bloquée dans une cabine d'ascenseur"),
    CODE_423("ASSISTANCE_A_PERSONNES", "Dégagement d'une personne ou d'un objet en hauteur (parachute, etc.)"),
    CODE_424("ASSISTANCE_A_PERSONNES", "Effondrement ou Eboulement (bâtiment - troue-abri)"),
    CODE_501("FAIT_D'ANIMAUX", "Reconnaissances d'essaim d'abeilles, de guêpes ou de nuisibles"),
    CODE_502("FAIT_D'ANIMAUX", "Destruction d'essaim d'abeilles, de guêpes ou de nuisibles"),
    CODE_503("FAIT_D'ANIMAUX", "Sauvetage, capture, dégagement d'animal en difficulté"),
    CODE_611("EAU_-_GAZ_-_ELECTRICITE_-_AIR_COMPRIME", "Epuisement, assèchement d'un local"),
    CODE_612("EAU_-_GAZ_-_ELECTRICITE_-_AIR_COMPRIME", "Barrage ou colmatage d'une conduite d'eau"),
    CODE_613("EAU_-_GAZ_-_ELECTRICITE_-_AIR_COMPRIME", "Inondation importante"),
    CODE_614("EAU_-_GAZ_-_ELECTRICITE_-_AIR_COMPRIME", "Coulée de boue"),
    CODE_621("GAZ_AIR_COMPRIME", "Ventilation d'un local renfermant des gaz"),
    CODE_622("GAZ_AIR_COMPRIME", "Fermeture d'une bouteille de gaz non enflammée"),
    CODE_623("GAZ_AIR_COMPRIME", "Barrage d'une conduite d'air comprimé"),
    CODE_624("GAZ_AIR_COMPRIME", "Fuite d'essence dans un local"),
    CODE_625("GAZ_AIR_COMPRIME", "Explosion sans feu"),
    CODE_631("ELECTRICITE", "Court-circuit sans feu"),
    CODE_632("ELECTRICITE", "Fils électriques tombés sur la voie publique"),
    CODE_701("PROTECTION_DES_BIENS", "Dispersion, sablage ou lavage de produit répandu sur la voie publique"),
    CODE_702("PROTECTION_DES_BIENS", "Dégagement de matériel d'obstacle entravant la circulation"),
    CODE_703("PROTECTION_DES_BIENS", "Etaiement, bâchage ou déblaiement"),
    CODE_704("PROTECTION_DES_BIENS", "Amarrage, enlèvement, dépose de gravas menaçant de chuter"),
    CODE_801("LUTTE_CONTRE_LA_POLLUTION", "Canalisation ou évacuation d'hydrocarbure"),
    CODE_802("LUTTE_CONTRE_LA_POLLUTION", "Pollution sur plan d'eau ou cours d'eau"),
    CODE_803("LUTTE_CONTRE_LA_POLLUTION", "Autres interventions concernant la pollution (préciser)"),
    CODE_804("LUTTE_CONTRE_LA_POLLUTION", "Intervention NRBCE"),
    CODE_901("RECONNAISSANCES_OU_RECHERCHES", "Odeur suspecte"),
    CODE_902("RECONNAISSANCES_OU_RECHERCHES", "Recherche d'objets de valeur (dans une fosse, ou dans n'importe quel lieu"),
    CODE_903("RECONNAISSANCES_OU_RECHERCHES", "Personne ne répondant pas aux appels"),
    CODE_904("RECONNAISSANCES_OU_RECHERCHES", "Fumée suspecte"),
    CODE_905("RECONNAISSANCES_OU_RECHERCHES", "Bruit suspect"),
    CODE_906("RECONNAISSANCES_OU_RECHERCHES", "Lueur suspecte"),
    CODES_X01("AUTRE", "Autre(Compléter dans les commentaires)");

    private final String category;

    private final String type;


}
