package bf.bnsp.api.tools.dataType;

public enum EEnginType {
    PREMIER_SECOURS,
    FOURGON,
    PREMIER_SECOURS_RELEVABLE,
    INTERVENTION_DIVERSE,
    DESINCARCERATION,
    ECHELLE,
    CANOT_SAUVETAGE_LEGER,
    CITERNE,
}
