package bf.bnsp.api.tools.dataType;

public enum EGrade {

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : HOMME DE RANG
    AUXILIAIRE,
    SAPEUR_2eme_CLASSE,
    SAPEUR_1ere_CLASSE,
    CAPORAL,
    CAPORAL_CHEF,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : SOUS-OFFICIER
    SERGENT,
    SERGENT_CHEF,
    ADJUDANT,
    ADJUDANT_CHEF,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : OFFICIER
    LIEUTENANT_HORS_CLASSE,
    LIEUTENANT_2eme_CLASSE,
    LIEUTENANT_1ere_CLASSE,
    CAPITAINE,
    COMMANDANT,
    LIEUTENANT_COLONEL,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : DIRECTION
    COLONEL,
    COLONEL_HORS_CLASSE,
    CONTROLEUR_GENERAL,
    INSPECTEUR_GENERAL
}
