package bf.bnsp.api.tools.dataType;

/**
 * @author Berickal
 */
public enum EGrade {

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : HOMME DE RANG
    SND,
    SAPEUR_2eme_CLASSE,
    SAPEUR_1ere_CLASSE,
    CAPORAL,
    CAPORAL_CHEF,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : SOUS-OFFICIER
    SERGENT,
    SERGENT_CHEF,
    ADJUDANT,
    ADJUDANT_CHEF,
    ADJUDANT_CHEF_MAJOR,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : OFFICIER
    SOUS_LIEUTENANT,
    LIEUTENANT,
    CAPITAINE,
    COMMANDANT,
    LIEUTENANT_COLONEL,

    //SAPEUR POMPIER VOLONTAIRE OU PROFESSIONEL : DIRECTION
    COLONEL,
    COLONEL_MAJOR
}
