package bf.bnsp.api.tools.dataType;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum EZoneCaserne {

    ZONE_000("Nord", "Tin Akof"),
    ZONE_001("Nord", "Markoye"),
    ZONE_002("Nord", "Oursi 1"),
    ZONE_003("Nord", "Deou"),
    ZONE_004("Nord", "Koutougou"),
    ZONE_005("Nord", "Falangoutou"),
    ZONE_006("Nord", "Nassoumbou"),
    ZONE_007("Nord", "Tongomaye"),
    ZONE_008("Nord", "Kelbo"),
    ZONE_009("Nord", "Arbinda"),
    ZONE_010("Nord", "Gorgadji"),
    ZONE_011("Nord", "Bani-Kallo"),
    ZONE_012("Nord", "Dori"),
    ZONE_013("Nord", "Seytenga"),
    ZONE_014("Nord", "Titabe"),
    ZONE_015("Nord", "Solhan"),
    ZONE_016("Nord", "Tankougounadie"),
    ZONE_017("Nord", "Boundoré"),
    ZONE_018("Nord", "Mansila"),
    ZONE_019("Est", "Kogho"),
    ZONE_020("Est", "Meguet"),
    ZONE_021("Est", "Zam"),
    ZONE_022("Est", "Mogtedo"),
    ZONE_023("Est", "Boudry"),
    ZONE_024("Est", "Zorgho"),
    ZONE_025("Est", "Kando"),
    ZONE_026("Est", "Pouytenga"),
    ZONE_027("Est", "Zoungou"),
    ZONE_028("Est", "Andemtenga"),
    ZONE_029("Est", "Yargo"),
    ZONE_030("Est", "Tensobentenga"),
    ZONE_031("Est", "Dialgaye"),
    ZONE_032("Est", "Komtoega"),
    ZONE_033("Est", "Beguedo"),
    ZONE_034("Est", "Boussouma"),
    ZONE_035("Est", "Bagre"),
    ZONE_036("Est", "Zonse"),
    ZONE_037("Est", "Zabre"),
    ZONE_038("Est", "Zoaga"),
    ZONE_039("Est", "Yargatenga"),
    ZONE_040("Est", "Bane"),
    ZONE_050("Est", "Bissiga"),
    ZONE_051("Est", "Lalgaye"),
    ZONE_052("Est", "Dourtenga"),
    ZONE_053("Est", "Ouargaye"),
    ZONE_054("Est", "Yargatenga"),
    ZONE_055("Est", "Sangha"),
    ZONE_056("Est", "Soudougui"),
    ZONE_057("Est", "Yonde"),
    ZONE_058("Est", "Comin-Yanga"),
    ZONE_059("Est", "Diabo"),
    ZONE_060("Est", "Gounghin"),
    ZONE_061("Est", "Diapangou"),
    ZONE_062("Est", "Pama"),
    ZONE_063("Est", "Kompiana"),
    ZONE_064("Est", "Modjoari"),
    ZONE_065("Est", "Logobou"),
    ZONE_066("Est", "Tambaga"),
    ZONE_067("Est", "Tansarga"),
    ZONE_068("Est", "Namgouangou"),
    ZONE_069("Est", "Daipaga"),
    ZONE_070("Est", "Kantchari"),
    ZONE_071("Est", "Botou"),
    ZONE_072("Est", "Matiacoali"),
    ZONE_073("Est", "Foutouri"),
    ZONE_074("Est", "Bartibougou"),
    ZONE_075("Centre", "Bourzanga"),
    ZONE_076("Centre", "Rollo"),
    ZONE_077("Centre", "Tikare"),
    ZONE_078("Centre", "Rouko"),
    ZONE_079("Centre", "Guibare"),
    ZONE_080("Centre", "Mane Mossi"),
    ZONE_081("Centre", "Boussouma"),
    ZONE_082("Centre", "Korsimoro"),
    ZONE_083("Centre", "Ziga"),
    ZONE_084("Centre", "Boala"),
    ZONE_085("Centre", "Pibaore"),
    ZONE_086("Centre", "Zeguedeguin Mossi"),
    ZONE_087("Centre", "Thion"),
    ZONE_088("Centre", "Mani"),
    ZONE_089("Centre", "Coalla"),
    ZONE_090("Centre", "Liptougou"),
    ZONE_091("Centre", "Yalogo"),
    ZONE_092("Centre", "Nagbingou 1"),
    ZONE_093("Centre", "Bouroum"),
    ZONE_094("Centre", "Tougouri"),
    ZONE_095("Centre", "Pensa"),
    ZONE_096("Centre", "Barsalogo"),
    ZONE_097("Centre", "Pissila"),
    ZONE_098("Centre", "Kaya"),
    ZONE_099("Centre", "Dablo"),
    ZONE_100("Centre", "Namissiguima"),
    ZONE_101("Centre", "Zimtenga"),
    ZONE_102("Centre", "Nassere"),
    ZONE_103("Centre", "Sabce"),
    ZONE_104("Centre", "Kongoussi"),
    ZONE_105("Sud", "Tema"),
    ZONE_106("Sud", "Arbole"),
    ZONE_107("Sud", "Niou"),
    ZONE_108("Sud", "Toeghin"),
    ZONE_109("Sud", "Bousse"),
    ZONE_110("Sud", "Pella"),
    ZONE_111("Sud", "Zitenga"),
    ZONE_112("Sud", "Sigle"),
    ZONE_113("Sud", "Pabre"),
    ZONE_114("Sud", "Loumbila"),
    ZONE_115("Sud", "Ziniare"),
    ZONE_116("Sud", "Tanghin Dassouri"),
    ZONE_117("Sud", "Bingo"),
    ZONE_118("Sud", "Sourgoubila"),
    ZONE_119("Sud", "Komki Ipala"),
    ZONE_120("Sud", "Koubri"),
    ZONE_121("Sud", "Kombissiri"),
    ZONE_122("Sud", "Doulougou"),
    ZONE_123("Sud", "Sapone (Karkouidiguen)"),
    ZONE_124("Sud", "Kayao"),
    ZONE_125("Sud", "Doulougou"),
    ZONE_126("Sud", "Ipelce"),
    ZONE_127("Sud", "Gaongo"),
    ZONE_128("Sud", "Bere"),
    ZONE_129("Sud", "Toece"),
    ZONE_130("Sud", "Guiba"),
    ZONE_131("Sud", "Manga"),
    ZONE_132("Sud", "Gogo"),
    ZONE_133("Sud", "Gomboussougou"),
    ZONE_134("Sud", "Guiaro"),
    ZONE_135("Sud", "Po"),
    ZONE_136("Sud", "Tiebele"),
    ZONE_137("Sud", "Zeko"),
    ZONE_138("Sud", "Ziou"),
    ZONE_139("Nord-Ouest", "Diguel"),
    ZONE_140("Nord-Ouest", "Baraboule"),
    ZONE_141("Nord-Ouest", "Solle Foulbe"),
    ZONE_142("Nord-Ouest", "Banh"),
    ZONE_143("Nord-Ouest", "Koumbri"),
    ZONE_144("Nord-Ouest", "Barga"),
    ZONE_145("Nord-Ouest", "Titao"),
    ZONE_146("Nord-Ouest", "Ouindigui"),
    ZONE_147("Nord-Ouest", "Seguenega"),
    ZONE_148("Nord-Ouest", "Kossouka"),
    ZONE_149("Nord-Ouest", "Rambo"),
    ZONE_150("Nord-Ouest", "Kalsaka"),
    ZONE_151("Nord-Ouest", "Kirsi"),
    ZONE_152("Nord-Ouest", "Tougou"),
    ZONE_153("Nord-Ouest", "Bassi"),
    ZONE_154("Nord-Ouest", "Leba"),
    ZONE_155("Nord-Ouest", "Oula"),
    ZONE_156("Nord-Ouest", "Zogore"),
    ZONE_157("Nord-Ouest", "Lankoue"),
    ZONE_158("Nord-Ouest", "Boussou"),
    ZONE_159("Nord-Ouest", "Gomponson"),
    ZONE_160("Nord-Ouest", "La-Tondin"),
    ZONE_161("Nord-Ouest", "Bagare"),
    ZONE_162("Nord-Ouest", "Yaba"),
    ZONE_163("Nord-Ouest", "Toma"),
    ZONE_164("Nord-Ouest", "Gossina"),
    ZONE_165("Nord-Ouest", "Kougny"),
    ZONE_166("Nord-Ouest", "Lanfiera"),
    ZONE_167("Nord-Ouest", "Kassoum"),
    ZONE_168("Nord-Ouest", "Di"),
    ZONE_169("Nord-Ouest", "Gomboro"),
    ZONE_170("Nord-Ouest", "Tangaye"),
    ZONE_171("Nord-Ouest", "Thiou"),
    ZONE_172("Nord-Ouest", "Kain"),
    ZONE_173("Boucle du Mouhoun", "Kombori"),
    ZONE_174("Boucle du Mouhoun", "Barani"),
    ZONE_175("Boucle du Mouhoun", "Djibasso"),
    ZONE_176("Boucle du Mouhoun", "Madouba"),
    ZONE_177("Boucle du Mouhoun", "Bomborokuy"),
    ZONE_178("Boucle du Mouhoun", "Doumbala"),
    ZONE_179("Boucle du Mouhoun", "Nouna"),
    ZONE_180("Boucle du Mouhoun", "Sono"),
    ZONE_181("Boucle du Mouhoun", "Dokuy"),
    ZONE_182("Boucle du Mouhoun", "Bourasso"),
    ZONE_183("Boucle du Mouhoun", "Douroula"),
    ZONE_184("Boucle du Mouhoun", "Warkoye"),
    ZONE_185("Boucle du Mouhoun", "Kona"),
    ZONE_186("Boucle du Mouhoun", "Godyr"),
    ZONE_187("Boucle du Mouhoun", "Pilimpikou"),
    ZONE_188("Boucle du Mouhoun", "Didyr"),
    ZONE_189("Boucle du Mouhoun", "Kordye"),
    ZONE_190("Boucle du Mouhoun", "Dassa"),
    ZONE_191("Boucle du Mouhoun", "Soaw"),
    ZONE_192("Boucle du Mouhoun", "Kindi"),
    ZONE_193("Boucle du Mouhoun", "Reo"),
    ZONE_194("Boucle du Mouhoun", "Kyon"),
    ZONE_195("Boucle du Mouhoun", "Nandiala"),
    ZONE_196("Boucle du Mouhoun", "Ramongo"),
    ZONE_197("Boucle du Mouhoun", "Sourgou"),
    ZONE_198("Boucle du Mouhoun", "Sabou"),
    ZONE_199("Boucle du Mouhoun", "Thyou"),
    ZONE_200("Boucle du Mouhoun", "Pouni"),
    ZONE_201("Boucle du Mouhoun", "Zamo"),
    ZONE_202("Boucle du Mouhoun", "Tenado"),
    ZONE_203("Boucle du Mouhoun", "Nebielianayou"),
    ZONE_204("Boucle du Mouhoun", "Zawara"),
    ZONE_205("Boucle du Mouhoun", "Dalo"),
    ZONE_206("Boucle du Mouhoun", "Bakata"),
    ZONE_207("Boucle du Mouhoun", "Cassou"),
    ZONE_208("Boucle du Mouhoun", "Silly"),
    ZONE_209("Boucle du Mouhoun", "Niabouri"),
    ZONE_210("Boucle du Mouhoun", "Boura"),
    ZONE_211("Boucle du Mouhoun", "Leo"),
    ZONE_212("Boucle du Mouhoun", "Bieha"),
    ZONE_213("Haut Bassin", "Ouri"),
    ZONE_214("Haut Bassin", "Siby"),
    ZONE_215("Haut Bassin", "Pompoi"),
    ZONE_216("Haut Bassin", "Bana"),
    ZONE_217("Haut Bassin", "Yaho"),
    ZONE_218("Haut Bassin", "Boromo"),
    ZONE_219("Haut Bassin", "Fara"),
    ZONE_220("Haut Bassin", "Koti"),
    ZONE_221("Haut Bassin", "Founzan"),
    ZONE_222("Haut Bassin", "Hounde"),
    ZONE_223("Haut Bassin", "Boho-Bereba"),
    ZONE_224("Haut Bassin", "Bekuy"),
    ZONE_225("Haut Bassin", "Oronkua"),
    ZONE_226("Haut Bassin", "Gueguere"),
    ZONE_227("Haut Bassin", "Koper"),
    ZONE_228("Haut Bassin", "Niego"),
    ZONE_229("Haut Bassin", "Dissin"),
    ZONE_230("Haut Bassin", "Diebougou"),
    ZONE_231("Haut Bassin", "Tiankoura"),
    ZONE_232("Haut Bassin", "Zambo"),
    ZONE_233("Haut Bassin", "Nako"),
    ZONE_234("Haut Bassin", "Bouroum-Bouroum"),
    ZONE_235("Haut Bassin", "Malba"),
    ZONE_236("Haut Bassin", "Boussera"),
    ZONE_237("Haut Bassin", "Gbomblora"),
    ZONE_238("Haut Bassin", "Legmoin"),
    ZONE_239("Haut Bassin", "Midebdo"),
    ZONE_240("Haut Bassin", "Batie"),
    ZONE_241("Haut Bassin", "Boussoukoula"),
    ZONE_242("Haut Bassin", "Kpere"),
    ZONE_243("Haut Bassin", "Gaoua"),
    ZONE_244("Ouest", "Tansila"),
    ZONE_245("Ouest", "Balave"),
    ZONE_246("Ouest", "Sanaba"),
    ZONE_247("Ouest", "Sami"),
    ZONE_248("Ouest", "Faramana"),
    ZONE_249("Ouest", "Kouka"),
    ZONE_250("Ouest", "Fo"),
    ZONE_251("Ouest", "Kayan"),
    ZONE_252("Ouest", "Koundougou"),
    ZONE_253("Ouest", "Padema"),
    ZONE_254("Ouest", "Satiri"),
    ZONE_255("Ouest", "Lena"),
    ZONE_256("Ouest", "Bama"),
    ZONE_257("Ouest", "Dande"),
    ZONE_258("Ouest", "N'Dorola"),
    ZONE_259("Ouest", "Morolaba"),
    ZONE_260("Ouest", "Sindo"),
    ZONE_261("Ouest", "Samorogouan"),
    ZONE_262("Ouest", "Djigouera"),
    ZONE_263("Ouest", "Karangassa-Sambla"),
    ZONE_264("Ouest", "Peni"),
    ZONE_265("Ouest", "Karangasso-Vigue"),
    ZONE_266("Ouest", "Bondigui"),
    ZONE_267("Ouest", "Dolo"),
    ZONE_268("Sud", "Kangala"),
    ZONE_269("Sud", "Oueleni"),
    ZONE_270("Sud", "Kankalaba"),
    ZONE_271("Sud", "Loumana"),
    ZONE_272("Sud", "Douna"),
    ZONE_273("Sud", "Dakoro"),
    ZONE_274("Sud", "Wolonkoto"),
    ZONE_275("Sud", "Moussodougou"),
    ZONE_276("Sud", "Samogoyiti"),
    ZONE_277("Sud", "Kourimon"),
    ZONE_278("Sud", "Beregadougou"),
    ZONE_279("Sud", "Toussiana"),
    ZONE_280("Sud", "Tiefora"),
    ZONE_281("Sud", "Banfora"),
    ZONE_282("Sud", "Soubalaniodougou"),
    ZONE_283("Sud", "Niangoloko"),
    ZONE_284("Sud", "Mangodara"),
    ZONE_285("Sud", "Sideradougou"),
    ZONE_286("Sud", "Ouo"),
    ZONE_287("Sud", "Loropeni"),
    ZONE_288("Sud", "Kampti"),
    ZONE_289("Sud", "Djigoue"),
    ZONE_290("Sud", "Perigban");

    private String region;

    private String zone;
}
