package bf.bnsp.api.tools.dataType;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum EZoneCaserne {

    ZONE_000("Nord", "Tin Akof"),
    ZONE_001("Nord", "Markoye"),
    ZONE_002("Nord", "Oursi 1"),
    ZONE_003("Nord", "Deou"),
    ZONE_004("Nord", "Koutougou"),
    ZONE_005("Nord", "Falangoutou"),
    ZONE_006("Nord", "Nassoumbou"),
    ZONE_007("Nord", "Tongomaye"),
    ZONE_008("Nord", "Kelbo"),
    ZONE_009("Nord", "Arbinda"),
    ZONE_010("Nord", "Gorgadji"),
    ZONE_011("Nord", "Bani-Kallo"),
    ZONE_012("Nord", "Dori"),
    ZONE_013("Nord", "Seytenga"),
    ZONE_014("Nord", "Titabe"),
    ZONE_015("Nord", "Solhan"),
    ZONE_016("Nord", "Tankougounadie"),
    ZONE_017("Nord", "Boundoré"),
    ZONE_018("Nord", "Mansila"),
    ZONE_019("Est", "Kogho"),
    ZONE_020("Est", "Meguet"),
    ZONE_021("Est", "Zam"),
    ZONE_022("Est", "Mogtedo"),
    ZONE_023("Est", "Boudry"),
    ZONE_024("Est", "Zorgho"),
    ZONE_025("Est", "Kando"),
    ZONE_026("Est", "Pouytenga"),
    ZONE_027("Est", "Zoungou"),
    ZONE_028("Est", "Andemtenga"),
    ZONE_029("Est", "Yargo"),
    ZONE_030("Est", "Tensobentenga"),
    ZONE_031("Est", "Dialgaye"),
    ZONE_032("Est", "Komtoega"),
    ZONE_033("Est", "Beguedo"),
    ZONE_034("Est", "Boussouma"),
    ZONE_035("Est", "Bagre"),
    ZONE_036("Est", "Zonse"),
    ZONE_037("Est", "Zabre"),
    ZONE_038("Est", "Zoaga"),
    ZONE_039("Est", "Yargatenga"),
    ZONE_040("Est", "Bane"),
    ZONE_050("Est", "Bissiga"),
    ZONE_051("Est", "Lalgaye"),
    ZONE_052("Est", "Dourtenga"),
    ZONE_053("Est", "Ouargaye"),
    ZONE_054("Est", "Yargatenga"),
    ZONE_055("Est", "Sangha"),
    ZONE_056("Est", "Soudougui"),
    ZONE_057("Est", "Yonde"),
    ZONE_058("Est", "Comin-Yanga"),
    ZONE_059("Est", "Diabo"),
    ZONE_060("Est", "Gounghin"),
    ZONE_061("Est", "Diapangou"),
    ZONE_062("Est", "Pama"),
    ZONE_063("Est", "Kompiana"),
    ZONE_064("Est", "Modjoari"),
    ZONE_065("Est", "Logobou"),
    ZONE_066("Est", "Tambaga"),
    ZONE_067("Est", "Tansarga"),
    ZONE_068("Est", "Namgouangou"),
    ZONE_069("Est", "Daipaga"),
    ZONE_070("Est", "Kantchari"),
    ZONE_071("Est", "Botou"),
    ZONE_072("Est", "Matiacoali"),
    ZONE_073("Est", "Foutouri"),
    ZONE_074("Est", "Bartibougou"),
    ZONE_075("Centre", "Bourzanga"),
    ZONE_076("Centre", "Rollo"),
    ZONE_077("Centre", "Tikare"),
    ZONE_078("Centre", "Rouko"),
    ZONE_079("Centre", "Guibare"),
    ZONE_080("Centre", "Mane Mossi"),
    ZONE_081("Centre", "Boussouma"),
    ZONE_082("Centre", "Korsimoro"),
    ZONE_083("Centre", "Ziga"),
    ZONE_084("Centre", "Boala"),
    ZONE_085("Centre", "Pibaore"),
    ZONE_086("Centre", "Zeguedeguin Mossi"),
    ZONE_087("Centre", "Thion"),
    ZONE_088("Centre", "Mani"),
    ZONE_089("Centre", "Coalla"),
    ZONE_090("Centre", "Liptougou"),
    ZONE_091("Centre", "Yalogo"),
    ZONE_092("Centre", "Nagbingou 1"),
    ZONE_093("Centre", "Bouroum"),
    ZONE_094("Centre", "Tougouri"),
    ZONE_095("Centre", "Pensa"),
    ZONE_096("Centre", "Barsalogo"),
    ZONE_097("Centre", "Pissila"),
    ZONE_098("Centre", "Kaya"),
    ZONE_099("Centre", "Dablo"),
    ZONE_100("Centre", "Namissiguima"),
    ZONE_101("Centre", "Zimtenga"),
    ZONE_102("Centre", "Nassere"),
    ZONE_103("Centre", "Sabce"),
    ZONE_104("Centre", "Kongoussi"),
    ZONE_105("Sud", "Tema"),
    ZONE_106("Sud", "Arbole"),
    ZONE_107("Sud", "Niou"),
    ZONE_108("Sud", "Toeghin"),
    ZONE_109("Sud", "Bousse"),
    ZONE_110("Sud", "Pella"),
    ZONE_111("Sud", "Zitenga"),
    ZONE_112("Sud", "Sigle"),
    ZONE_113("Sud", "Pabre"),
    ZONE_114("Sud", "Loumbila"),
    ZONE_115("Sud", "Ziniare"),
    ZONE_116("Sud", "Tanghin Dassouri"),
    ZONE_117("Sud", "Bingo"),
    ZONE_118("Sud", "Sourgoubila"),
    ZONE_119("Sud", "Komki Ipala"),
    ZONE_120("Sud", "Koubri"),
    ZONE_121("Sud", "Kombissiri"),
    ZONE_122("Sud", "Doulougou"),
    ZONE_123("Sud", "Sapone (Karkouidiguen)"),
    ZONE_124("Sud", "Kayao"),
    ZONE_125("Sud", "Doulougou"),
    ZONE_126("Sud", "Ipelce"),
    ZONE_127("Sud", "Gaongo"),
    ZONE_128("Sud", "Bere"),
    ZONE_129("Sud", "Toece"),
    ZONE_130("Sud", "Guiba"),
    ZONE_131("Sud", "Manga"),
    ZONE_132("Sud", "Gogo"),
    ZONE_133("Sud", "Gomboussougou"),
    ZONE_134("Sud", "Guiaro"),
    ZONE_135("Sud", "Po"),
    ZONE_136("Sud", "Tiebele"),
    ZONE_137("Sud", "Zeko"),
    ZONE_138("Sud", "Ziou"),
    ZONE_139("Nord-Ouest", "Diguel"),
    ZONE_140("Nord-Ouest", "Baraboule"),
    ZONE_141("Nord-Ouest", "Solle Foulbe"),
    ZONE_142("Nord-Ouest", "Banh"),
    ZONE_143("Nord-Ouest", "Koumbri"),
    ZONE_144("Nord-Ouest", "Barga"),
    ZONE_145("Nord-Ouest", "Titao"),
    ZONE_146("Nord-Ouest", "Ouindigui"),
    ZONE_147("Nord-Ouest", "Seguenega"),
    ZONE_148("Nord-Ouest", "Kossouka"),
    ZONE_149("Nord-Ouest", "Rambo"),
    ZONE_150("Nord-Ouest", "Kalsaka"),
    ZONE_151("Nord-Ouest", "Kirsi"),
    ZONE_152("Nord-Ouest", "Tougou"),
    ZONE_153("Nord-Ouest", "Bassi"),
    ZONE_154("Nord-Ouest", "Leba"),
    ZONE_155("Nord-Ouest", "Oula"),
    ZONE_156("Nord-Ouest", "Zogore"),
    ZONE_157("Nord-Ouest", "Lankoue"),
    ZONE_158("Nord-Ouest", "Boussou"),
    ZONE_159("Nord-Ouest", "Gomponson"),
    ZONE_160("Nord-Ouest", "La-Tondin"),
    ZONE_161("Nord-Ouest", "Bagare"),
    ZONE_162("Nord-Ouest", "Yaba"),
    ZONE_163("Nord-Ouest", "Toma"),
    ZONE_164("Nord-Ouest", "Gossina"),
    ZONE_165("Nord-Ouest", "Kougny"),
    ZONE_166("Nord-Ouest", "Lanfiera"),
    ZONE_167("Nord-Ouest", "Kassoum"),
    ZONE_168("Nord-Ouest", "Di"),
    ZONE_169("Nord-Ouest", "Gomboro"),
    ZONE_170("Nord-Ouest", "Tangaye"),
    ZONE_171("Nord-Ouest", "Thiou"),
    ZONE_172("Nord-Ouest", "Kain");

    private String region;

    private String zone;
}
